spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false